import {Container} from 'typescript-ioc';
import {FormApi} from './form/displayform.api';
import {MockFormApi} from './form/displayform.mock.api';
import {FormMock} from './form/displayform.mock';
import {FormService} from './form/displayform.service';
export * from './form/displayform.api';
export * from './form/displayform.mock.api';
export * from './form/displayform.mock';
export * from './form/displayform.service';
Container.bind(MockFormApi).to(FormMock);
Container.bind(FormApi).to(FormService);